# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Make new Release from the block
      run: |
       curl 'https://app.yonohub.com/api/yonoarc/blockbuilder/projects/5ef4c7579c5c94c282d3c6a9' \
        -X 'PATCH' \
        -H 'authority: app.yonohub.com' \
        -H 'accept: application/json, text/plain, */*' \
        -H 'authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTI5MjA2MTYsIm5iZiI6MTU5MjkyMDYxNiwianRpIjoiYTMyNWU5NWItMmM5Yy00N2JmLTg0NGEtZGNmNWY4NGI5ZTk0IiwiZXhwIjoxNTk1NTEyNjE2LCJpZGVudGl0eSI6IjViYTBlMjdmYTYyNjg2MDAxYWY3Nzk2ZSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.tmQujydH_lk28e05jXpdeKkBUtnLDNmuV-OrH_w1axM' \
        -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36' \
        -H 'content-type: application/json' \
        -H 'origin: https://app.yonohub.com' \
        -H 'sec-fetch-site: same-origin' \
        -H 'sec-fetch-mode: cors' \
        -H 'sec-fetch-dest: empty' \
        -H 'referer: https://app.yonohub.com/blockbuilder/' \
        -H 'accept-language: en-US,en;q=0.9,de;q=0.8,ar;q=0.7' \
        -H 'cookie: experimentation_subject_id=IjQ2NmIyNTgwLWQ1MDAtNGViYi1hNWY0LTEzYzMxYjIwNGI4OSI%3D--c8adc799f1e4878f9a39cd1c1052e6c5bb3a22c7; tk_or=%22https%3A%2F%2Fapp.yonohub.com%2Fblockbuilder%2F%22; _ga=GA1.2.839258031.1575754454; tk_ai=3KzxuK%2FLmTMVDpr8PfN%2FizCO; tk_r3d=%22https%3A%2F%2Fwww.google.com%2F%22; tk_lr=%22https%3A%2F%2Fwww.google.com%2F%22' \
        --data-binary '{"all_versions":[{"description":"","is_deleted":false,"release_at":"2020/6/25, 16:13","version_no":"0.0.1-x86_64"},{"description":"","is_deleted":false,"release_at":"2020/6/30, 12:03","version_no":"0.0.2-x86_64"}],"creator_user_id":"5ba0e27fa62686001af7796e","creator_username":"Ibrahim Essam","dep_reg_launch_settings":{},"environment":{"id":"5ef4c1a879d1ff6415194bf9","original_env_id":"5eea034979d1ff6415194bce"},"file_path_type":"gitrepo","gitRepo":{"url":"git@gitlab.yonohub.com:ibrahimessam/rqt.git"},"id":"5ef4c7579c5c94c282d3c6a9","is_deleted":false,"is_shared":false,"latest_release_date":"2020/6/30, 12:03","log_path":"/MyDrive/Rqt.log","messages_repos":[{"branch":"0.1.1","url":"https://gitlab.yonohub.com/YonoTeam/yonoarc-msgs.git"},{"branch":"0.5.11","url":"https://gitlab.yonohub.com/YonoTeam/ros-std-msgs.git"},{"branch":"1.12.6","url":"https://gitlab.yonohub.com/YonoTeam/ros-common-msgs.git"}],"name":"Rqt","status":"released","type":"yonoarc","version":"0.0.2-x86_64","is_sharable":true,"instance":"C1"}' \
        --compressed
    - name: Build the Block
      run: |
        curl 'https://app.yonohub.com/api/yonoarc/blockbuilder/projects/5ef4c7579c5c94c282d3c6a9/build' \
          -H 'authority: app.yonohub.com' \
          -H 'accept: application/json, text/plain, */*' \
          -H 'authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTI5MjA2MTYsIm5iZiI6MTU5MjkyMDYxNiwianRpIjoiYTMyNWU5NWItMmM5Yy00N2JmLTg0NGEtZGNmNWY4NGI5ZTk0IiwiZXhwIjoxNTk1NTEyNjE2LCJpZGVudGl0eSI6IjViYTBlMjdmYTYyNjg2MDAxYWY3Nzk2ZSIsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.tmQujydH_lk28e05jXpdeKkBUtnLDNmuV-OrH_w1axM' \
          -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36' \
          -H 'content-type: application/json' \
          -H 'origin: https://app.yonohub.com' \
          -H 'sec-fetch-site: same-origin' \
          -H 'sec-fetch-mode: cors' \
          -H 'sec-fetch-dest: empty' \
          -H 'referer: https://app.yonohub.com/blockbuilder/' \
          -H 'accept-language: en-US,en;q=0.9,de;q=0.8,ar;q=0.7' \
          -H 'cookie: experimentation_subject_id=IjQ2NmIyNTgwLWQ1MDAtNGViYi1hNWY0LTEzYzMxYjIwNGI4OSI%3D--c8adc799f1e4878f9a39cd1c1052e6c5bb3a22c7; tk_or=%22https%3A%2F%2Fapp.yonohub.com%2Fblockbuilder%2F%22; _ga=GA1.2.839258031.1575754454; tk_ai=3KzxuK%2FLmTMVDpr8PfN%2FizCO; tk_r3d=%22https%3A%2F%2Fwww.google.com%2F%22; tk_lr=%22https%3A%2F%2Fwww.google.com%2F%22' \
          --data-binary '{"project":{"all_versions":[{"description":"","is_deleted":false,"release_at":"","version_no":"0.0.0"},{"description":"","is_deleted":false,"release_at":"2020/6/25, 16:13","version_no":"0.0.1-x86_64"},{"description":"","is_deleted":false,"release_at":"2020/6/30, 12:03","version_no":"0.0.2-x86_64"},{"description":"","is_deleted":false,"release_at":"2020/6/30, 12:11","version_no":"0.0.3-x86_64"}],"creator_user_id":"5ba0e27fa62686001af7796e","creator_username":"Ibrahim Essam","dep_reg_launch_settings":{},"environment":{"id":"5ef4c1a879d1ff6415194bf9","original_env_id":"5eea034979d1ff6415194bce"},"file_path_type":"gitrepo","gitRepo":{"url":"git@gitlab.yonohub.com:ibrahimessam/rqt.git"},"id":"5ef4c7579c5c94c282d3c6a9","is_deleted":false,"is_shared":false,"latest_release_date":"2020/6/30, 12:11","log_path":"/MyDrive/Rqt.log","messages_repos":[{"branch":"0.1.1","url":"https://gitlab.yonohub.com/YonoTeam/yonoarc-msgs.git"},{"branch":"0.5.11","url":"https://gitlab.yonohub.com/YonoTeam/ros-std-msgs.git"},{"branch":"1.12.6","url":"https://gitlab.yonohub.com/YonoTeam/ros-common-msgs.git"}],"name":"Rqt","status":"error","type":"yonoarc","version":"0.0.3-x86_64","is_sharable":true,"resources":{"cpu":1,"gpu":0,"memory":1},"instance":"C8"},"express":true,"log_path":"/MyDrive/Rqt.log"}' \
          --compressed
